name: Pull translations
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  pull-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: python pull_translations.py
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - run: .github/workflows/git_push.sh
